require("config.globals")
require("config.autocmds")
require("config.keymaps")
require("config.lsp")
require("config.colorscheme")
require("plugins.treesitter")
require("plugins.lspconfig")
require("plugins.oil")
require("plugins.mini.pick")
require("plugins.fzf")
require("plugins.markdown-preview")

